name: LeapShape - Build Site

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Cache Node Modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Node Modules
        run: npm install

      - name: Pre-Process Site
        run: |
          sed -e 's/\/src\//\/build\//g' index.html > index.html.tmp
          mv index.html.tmp index.html
          sed -e 's/\/\/import /import /g' src/Backend/mainWorker.js > src/Backend/mainWorker.js.tmp
          mv src/Backend/mainWorker.js.tmp src/Backend/mainWorker.js
          sed -e 's/importScripts /\/\/importScripts/g' src/Backend/mainWorker.js > src/Backend/mainWorker.js.tmp
          mv src/Backend/mainWorker.js.tmp src/Backend/mainWorker.js

      - name: Remove old WebAssembly
        working-directory: ./build
        continue-on-error: true
        run: rm -rf opencascade.wasm-*

      - name: Run esbuild
        run: npm run build

      - name: Commit the Updated Build Artifacts
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions"
          git add build
          git add index.html
          git add .github
          git diff-index --quiet HEAD || git commit -m "Rebuild Site"

      #- name: Push Changes to branch
      #  uses: ad-m/github-push-action@master
      #  with:
      #    github_token: ${{ secrets.GITHUB_TOKEN }}
      #    branch: gh-pages
      #    CLEAN: true # Automatically remove deleted files from the deploy branch

      # Push the contents of the html directory to the gh-pages branch 
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This is set by github, do not change.
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: . # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
